Five03Motorcycles/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from pages import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^marketplace/', include('marketplace.urls')),
    url(r'^$', views.index, name='index'),
    #url(r'^$', include('pages.urls')),
    url(r'^pages/', include('pages.urls'))
]

marketplace/urls.py
from django.conf.urls import url
from . import views

app_name = 'marketplace'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail')
]

pages/urls.py
from django.conf.urls import url
from . import views

app_name = 'pages'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^request/$', views.request, name='request'),
    url(r'^finance/$', views.finance, name='finance'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^thanks/$', views.thanks, name='thanks')
]

marketplace/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

TYPE_OF_BIKES_CHOICES = (
    ('Cruiser','Cruiser'),
    ('Supersport','Supersport'),
    ('Standard','Standard')
)

COLOR_CHOICES = (
    ('White','White'),
    ('Black','Black'),
    ('Red','Red'),
    ('Yellow','Yellow'),
    ('Blue','Blue'),
    ('Silver','Silver'),
    ('Grey','Grey'),
    ('Orange','Orange'),
    ('Green','Green')
)

def content_file_name(instance,filename):
    return ''.join(['marketplace/static/marketplace/pics/', str(instance.pk), '/', filename])
# Create your models here.
class Motorcycle(models.Model):
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    color = models.CharField(choices=COLOR_CHOICES,default='Black',max_length=50)
    year = models.IntegerField(default=2017)
    mileage = models.IntegerField(default=20)
    price = models.IntegerField(default=20000)
    engineSize = models.CharField(max_length=50)
    typeOfBike = models.CharField(choices=TYPE_OF_BIKES_CHOICES,default='Standard',max_length=50)
    antiLockBrakes = models.BooleanField(default=True)
    sold = models.BooleanField(default=False)
    pics = models.FileField(upload_to=content_file_name)
    pic_1 = models.FileField(upload_to=content_file_name)
    pic_2 = models.FileField(upload_to=content_file_name)
    pic_3 = models.FileField(upload_to=content_file_name)
    pic_4 = models.FileField(upload_to=content_file_name)
    pic_5 = models.FileField(upload_to=content_file_name)
    report = models.FileField(upload_to='uploads/reports')

    def __str__(self):
        return str(self.year) + " " + self.make + " " + self.model + " (ID=" + str(self.id) + ")"

pages/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

marketplace/forms.py
# make sure this is at the top if it isn't already
from django import forms

# our new form
class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=False)

pages/forms.py
# make sure this is at the top if it isn't already
from django import forms

# our new form
class RequestForm(forms.Form):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=True)
    budget = forms.IntegerField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

marketplace/views.py
from django.views import generic
from .models import Motorcycle
from django.shortcuts import render
from .filters import MotoFilter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ContactForm
from django.shortcuts import render, get_object_or_404

def index(request):
    bike_list = Motorcycle.objects.all()
    # moto_filter = MotoFilter(request.GET, queryset=bike_list)
    # paginator = Paginator(moto_filter.qs, 5)
    # page = request.GET.get('page')
    # try:
    #     bikes = paginator.page(page)
    # except PageNotAnInteger:
    #     bikes = paginator.page(1)
    # except EmptyPage:
    #     bikes = paginator.page(paginator.num_pages)

    return render(request, 'marketplace/index.html', context = {'bikes': bikes}) #{'filter': moto_filter,'bikes': bikes})

def detail(request, pk):
    form = ContactForm()
    motorcycle = Motorcycle.objects.get(pk=pk)
    return render(request, 'marketplace/detail.html', {'form': form, 'motorcycle': motorcycle})

pages/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from .forms import RequestForm
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.shortcuts import redirect
from django.template import Context

# Create your views here.
def index(request):
    return render(request, 'pages/index.html', context = {})

def contact(request):
    return render(request, 'pages/contact.html', context = {})

def finance(request):
    return render(request, 'pages/finance.html', context = {})

def about(request):
    return render(request, 'pages/about.html', context = {})

def thanks(request):
    return render(request, 'pages/thanks.html', context = { })

def request(request):
    if request.method == 'GET':
        form = RequestForm()
    else:
        form = RequestForm(request.POST)
        if form.is_valid():
            first_name = request.POST.get('first_name', '')
            last_name = request.POST.get('last_name', '')
            email = request.POST.get('email', '')
            phone = request.POST.get('phone', '')
            budget = request.POST.get('budget', '')
            content = request.POST.get('content', '')

            template = get_template('pages/request_template.txt')
            context = {
                'first_name': first_name,
                'last_name': last_name,
                'email': email,
                'phone': phone,
                'budget': budget,
                'content': content
            }
            content = template.render(context)
            email = EmailMessage("Motorcycle Request Form Submission",
                                content,
                                "Your website" +'',
                                ['crao.anshu@gmail.com'],
                                headers = {'Reply-To': email }
            )
            email.send()
            return redirect('pages:thanks')
    return render(request, 'pages/request.html', context = {'form': form})

marketplace/templates/marketplace/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}503 Motorcycles{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
	{% load staticfiles %}
	<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
			crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">

    <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>

    <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<!-- Optional theme -->
	<link rel="stylesheet" href="{% static 'marketplace/style.css' %}">
	<link rel="stylesheet" href="{% static 'marketplace/landing-page.css' %}">

</head>

<body>

    <!-- Navigation -->
	<nav class="navbar navbar-default navbar-fixed-top menu">
		<div class="navbar-header">
			<a href="{% url 'index' %}" class="navbar-brand logo-503">
				503Motorcycles
			</a>
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="container-fluid">
			<div id="myNavbar" class="collapse navbar-collapse container">
				<ul class="nav navbar-nav navbar-right">
					<li class="menu-item"><a href="{% url 'index' %}" class="item">Home</a></li>
					<li class="menu-item"><a href="{% url 'marketplace:index' %}" class="item">Marketplace</a></li>
					<li class="menu-item"><a href="{% url 'pages:finance' %}" class="item">Finance</a></li>
					<li class="menu-item"><a href="{% url 'pages:request' %}" class="item">Request</a></li>
					<li class="menu-item user"><a class="item"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Guest</a></li>
				</ul>
			</div>
		</div>
	</nav>

	<!-- Page Content -->
	{% block body %}
	{% endblock %}

	<div class="footer-wrap">
	<footer class="container-fluid footer">
		<div class="row footer-info">
			<div class="col-md-4 col-xs-12 footer-breaker">
				<h4 class="footerLink">Our Garage</h4>
				<a class="footer-page-link" href="{% url 'pages:about' %}"><h5>About Us</h5></a>
				<h5>Schedule Appointment</h5>
			</div>
			<div class="col-md-4 col-xs-12 footer-breaker">
				<h4 class="footerLink">Social Media</h4>
				<div class="row">
					<ul class="socialLinks">
						<li class="col-md-offset-3 col-md-2 col-xs-4"><a href="http://facebook.com" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
						<li class="col-md-2 col-xs-4"><a href="https://www.instagram.com/503motorcycles/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
						<li class="col-md-2 col-xs-4"><a href="https://www.linkedin.com/company-beta/24978859/" target="_blank"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="col-md-4 col-xs-12 footer-breaker">
				<h4 class="footerLink">Contact Us</h4>
				<h5><i class="fa fa-phone phone-icon" aria-hidden="true"></i> (469)-677-7949</h5>
				<h5><i class="fa fa-inbox phone-icon" aria-hidden="true"></i> <a class="footer-page-link" href="mailto:503motorcycles@gmail.com">503motorcycles@gmail.com</a></h5>
			</div>
		</div>
	</footer>
	</div>

</body>

</html>

marketplace/templates/marketplace/index.html
{% extends 'marketplace/base.html' %}

<title>{% block title %}503 Motorcycles Marketplace{% endblock %}</title>

{% load widget_tweaks %}

{% load mytemplatetags %}

{% load static %}

{% block body %}
    <script>
        $(document).ready(function(){
            $( ":input" ).removeClass('collapse');
            $("a.btn-custom").click(function(){
                var menu = $(this).attr('id');
                if($("#" + menu).find(".glyphicon").hasClass("glyphicon-menu-up")){
                    $("#" + menu).find(".glyphicon").removeClass("glyphicon-menu-up");
                    $("#" + menu).find(".glyphicon").addClass("glyphicon-menu-down");
                }
                else if($("#" + menu).find(".glyphicon").hasClass("glyphicon-menu-down")){
                    $("#" + menu).find(".glyphicon").removeClass("glyphicon-menu-down");
                    $("#" + menu).find(".glyphicon").addClass("glyphicon-menu-up");
                }
            });
        });
    </script>
    <script>
        $(function() {
            $( "#price-slider" ).slider({
               range:true,
               step: 500,
               min: 500,
               max: 25000,
               values: [ 4000, 20000 ],
               slide: function( event, ui ) {
                  $("#id_price_0").val(ui.values[ 0 ]);
                  $("#id_price_1").val(ui.values[ 1 ]);
               }
            });
            $( "#mileage-slider" ).slider({
               range:true,
               step: 5,
               min: 0,
               max: 100,
               values: [ 10, 80 ],
               slide: function( event, ui ) {
                  $("#id_mileage_0").val(ui.values[ 0 ]);
                  $("#id_mileage_1").val(ui.values[ 1 ]);
               }
            });
            $("#id_price_0").val($( "#price-slider" ).slider( "values", 0 ));
            $("#id_price_1").val($( "#price-slider" ).slider( "values", 1 ));
            $("#id_mileage_0").val($( "#mileage-slider" ).slider( "values", 0 ));
            $("#id_mileage_1").val($( "#mileage-slider" ).slider( "values", 1 ));
         });
    </script>
<div id="initialcontainer" class="container">    
    <div class="row">
        <h1 class="center">503 Motorcycles Marketplace</h1>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-2">
            <ul class="nav nav-pills nav-stacked">
                <li><h5 class="center results-count">Total Results: {{ bikes.object_list.count }}</h5></li>
                <br>
                <li>
                    <form id="searchbox" method="get">
                        <div class="input-group row search-marketplace">
                            {% render_field filter.form.bike class="form-control" maxlength="50" autocomplete="off" placeholder="Search" %}
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </div>
                    </form>
                </li>
                <form method="get">
                    <li><a id="filtermenu-make" class="btn btn-custom spacer" data-toggle="collapse" href="#id_make" role="button"><h4><span id="gylph" class="glyphicon glyphicon-menu-up" aria-hidden="true"></span> Make</h4></a></li>
                    <li>
                        {% render_field filter.form.make class="filter-options collapse in" %}
                    </li>
                    <li><a id="filtermenu-year" class="btn btn-custom" data-toggle="collapse" href="#id_year" role="button"><h4><span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span> Year</h4></a></li>
                    <li>
                        {% render_field filter.form.year class="filter-options collapse in" %}
                    </li>
                    <li><a id="filtermenu-mileage" class="btn btn-custom" data-toggle="collapse" href="#mileage" role="button"><h4><span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span> Mileage</h4></a></li>
                    <li>
                        <div id="mileage" class="collapse in">
                            <label for="mileage-slider" class="center">Mileage Range (in thousands)</label>
                            <div id = "mileage-slider"></div>
                            <br>
                            <div class="col-sm-10 col-sm-offset-1">
                                <input type="text" name="mileage_0" class="form-control ranger" id="id_mileage_0">
                                <input type="text" name="mileage_1" class="form-control ranger" id="id_mileage_1">
                            </div>
                        </div>
                    </li>
                    <li><a id="filtermenu-color" class="btn btn-custom" data-toggle="collapse" href="#id_color" role="button"><h4><span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span> Color</h4></a></li>
                    <li>
                        {% render_field filter.form.color class="filter-options custom-control collapse in" %}
                    </li>
                    <li><a id="filtermenu-type" class="btn btn-custom" data-toggle="collapse" href="#id_typeOfBike" role="button"><h4><span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span> Type</h4></a></li>
                    <li>
                        {% render_field filter.form.typeOfBike class="filter-options custom-control collapse in" %}
                    </li>
                    <li><a id="filtermenu-price" class="btn btn-custom" data-toggle="collapse" href="#price" role="button"><h4><span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span> Price</h4></a></li>
                    <li>
                        <div id="price" class="collapse in">
                            <label for="price-slider" class="center">Price Range ($)</label>
                            <div id = "price-slider"></div>
                            <br>
                            <div class="col-sm-10 col-sm-offset-1">
                                <input type="text" name="price_0" class="form-control ranger" id="id_price_0">
                                <input type="text" name="price_1" class="form-control ranger" id="id_price_1">
                            </div>
                        </div>
                    </li>
                    <li><a id="filtermenu-engine" class="btn btn-custom" data-toggle="collapse" href="#id_engineSize" role="button"><h4><span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span> Engine Size</h4></a></li>
                    <li>
                        {% render_field filter.form.engineSize class="filter-options custom-control collapse in" %}
                    </li>
                    <br>
                    <div class="text-center">
                        <button type="submit" class="apply-filter btn btn-primary"><i class="fa fa-sliders filter-icon"></i>Apply Filters</button>
                    </div>
                </form>
            </ul>
            <br>
            <br>
        </div>
        <div class="col-md-offset-1 col-md-9">
             <br>
                {% if bikes.object_list %}
                    {% for m in bikes.object_list %}
                        <div class="row">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    {% if m.sold %}
                                    <div class="alert alert-danger row col-xs-8 col-xs-offset-2 col-md-8 col-md-offset-2"><p class="text-center">SOLD</p></div>
                                    {% endif %}
                                    <div class="col-md-6">
                                        <img class="img-responsive" src="{{ m.pics.url|cut:"0" }}">
                                    </div>
                                    <div class="col-md-6">
                                        <div class="row"><a class="bike-title" href="{% url 'marketplace:detail' m.id %}"><h2 class="center">{{ m.year }} {{ m.make }} {{ m.model }}</h2></a></div>
                                        <div class="row"><h3 class="center"><span class="index-label">Price:</span> ${{ m.price }}</h3></div>
                                        <div class="row"><h3 class="center"><span class="index-label">Mileage:</span> {{ m.mileage }}K</h3></div>
                                        <br>
                                        <br>
                                        <div class="row center">
                                            <div class="container-fluid">
                                                <a href="{% url 'marketplace:detail' m.id %}"><button type="button" class="btn btn-primary btn-lg btn-block">Details</button></a>
                                            </div>
                                        </div>
                                        <br>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                        <h3>No Results</h3>
                {% endif %}
            <div class="row text-center col-md-12">
            <!-- <ul class="pagination pagination-lg">
                {% if bikes.has_previous %}
                    <li><a href="?page={{ bikes.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in bikes.paginator.page_range %}
                {% if bikes.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if bikes.has_next %}
                    <li><a href="?page={{ bikes.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul> -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

marketplace/templates/pages/about.html
{% extends 'marketplace/base.html' %}

{% block body %}
{% load static %}
<div id="initialcontainer" class="container">
<h1>About</h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
                <img class="img-responsive center-block" src="{% static 'pages/img/logo.png'%}">
    </div>
    <div class="col-md-6">
        <p class="about">We are a small motorcycle dealership that strives to change the 
            way used motorcycles are sold. The founders have carried over their 
            experiences from the used car industry, specifically on how technology 
            has significantly improved the car buying experience, to improve the 
            efficiency and transparency of the process for customers.</p>
    </div>
</div>
</div>
{% endblock %}

marketplace/templates/pages/index.html
{% extends 'marketplace/base.html' %}

{% block body %}

    <div class="intro-header frontpage">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1 class="logo-503">503 Motorcycles</h1>
                        <hr class="intro-divider">
                        <a href="{% url 'marketplace:index' %}" class="btn btn-danger btn-lg">Our Garage</span></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container -->
    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Shop for Used Motorcycles</h2>
                    <p class="lead">Whatever your dream bike is, if we don't have it we will get it for you. 
                        We have access to auctions across the country, so we will get you your dream bike.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    {% load static %}
                    <img class="img-responsive img-rounded" src="{% static 'pages/img/header.png' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->
    <div class="content-section-b">
        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">All the Top Models</h2>
                    <p class="lead">We carry some of the most popular bikes so come get yours before they're all gone!
                        Drop us a <a class="request-link" href="{% url 'pages:request' %}">request</a> if you don't see a 
                        bike that you love and we'll make your wish come true.
                        </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    {% load static %}
                    <img class="img-responsive img-rounded" src="{% static 'pages/img/frontpage_a.jpeg' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Shop With Peace of Mind</h2>
                    <p class="lead">Every bike we sell passes a safety inspection. 
                        We inspect every bike so you don't have any surprises later.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    {% load static %}
                    <img class="img-responsive img-rounded" src="{% static 'pages/img/frontpage_b.JPG' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->
{% endblock %}

marketplace/templates/pages/request.html
{% extends 'marketplace/base.html' %}

{% load widget_tweaks %}

{% block body %}
<script>
    $(document).ready(function () {
        $(".form-control").on("paste",function(e){
            e.preventDefault();
        });
    });
    function validate(){
        var e = event || window.event;  
        var key = e.keyCode || e.which;     
        if (key == 60 || key == 62 || key == 188 || key == 190) { 
           if (e.preventDefault) e.preventDefault(); 
           e.returnValue = false; 
        }
    }
    function validatePhone(){
        var allowed = [8,13,16,37,39,48,49,50,51,52,53,54,55,56,57,58,189];
        var e = event || window.event;  
        var key = e.keyCode || e.which;                      
        if (!allowed.includes(key)) { 
           if (e.preventDefault) e.preventDefault(); 
           e.returnValue = false; 
        }
    }
</script>
<div id="initialcontainer" class="container">
<div class="row">
    <h1 class="center">Request a Motorcycle</h1>
</div>
<br>
<section class="colored-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h3 class="section-heading">Can't find the bike you're looking for?</h3>
                <p class="text-faded">If there's a particular bike that you're looking for, we can get it for you! 
                    We have access to auctions across the country, so we will get you your dream bike.
                    Just provide us with some information on the motorcycle you want and we will get back to you.
                </p>
            </div>
        </div>
    </div>
</section>
<br>
<br>
<div class="panel panel-default panel-form col-md-10 col-md-offset-1">
    <div class="panel-body">
    <div class="container-fluid">
    <h4 class="center">Request Form</h4>
    <br>
    <form role="form" action="" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group row {% if form.name.errors %}has-error{% endif %}">
            <label for="id_name" class="label-request col-sm-3 col-form-label">Name<span class="required">*</span>:</label>
            <div class="col-sm-9">
                {% render_field form.name onKeyDown="validate()" class="form-control" autocomplete="false" placeholder="Name" %}
                {% if form.name.errors %}
                    <span class="help-block">
                    {% for error in form.name.errors %}{{ error }}{% endfor %}
                    </span>
                {% endif %}
            </div>
        </div>
        <br>
        <div class="form-group row {% if form.email.errors %}has-error{% endif %}">
            <label for="id_email" class="label-request col-sm-3 col-form-label">Email<span class="required">*</span>:</label>
            <div class="col-sm-9">
                {% render_field form.email class="form-control" autocomplete="false" placeholder="you@example.com" %}
                {% if form.email.errors %}
                    <span class="help-block">
                    {% for error in form.email.errors %}{{ error }}{% endfor %}
                    </span>
                {% endif %}
            </div>
        </div>
        <br>
        <div class="form-group row {% if form.phone.errors %}has-error{% endif %}">
            <label for="id_phone" class="label-request col-sm-3 col-form-label">Phone<span class="required">*</span>:</label>
            <div class="col-sm-9">
                {% render_field form.phone onKeyDown="validatePhone()" class="form-control" autocomplete="false" placeholder="555-555-5555" %}
                {% if form.phone.errors %}
                    <span class="help-block">
                    {% for error in form.phone.errors %}{{ error }}{% endfor %}
                    </span>
                {% endif %}
            </div>
        </div>
        <br>
        <div class="form-group row {% if form.budget.errors %}has-error{% endif %}">
            <label for="id_budget" class="label-request col-sm-3 col-form-label">Budget ($)<span class="required">*</span>:</label>
            <div class="col-sm-9">
                {% render_field form.budget class="form-control" autocomplete="false" placeholder="5000" %}
                <small class="form-text text-muted">What is your budget for this bike?</small>
                {% if form.budget.errors %}
                    <span class="help-block">
                    {% for error in form.budget.errors %}{{ error }}{% endfor %}
                    </span>
                {% endif %}
            </div>
        </div>
        <br>
        <div class="form-group row {% if form.content.errors %}has-error{% endif %}">
            <label for="id_content" class="label-request col-sm-3 col-form-label">Information<span class="required">*</span>:</label>
            <div class="col-sm-9">
                {% render_field form.content onKeyDown="validate()" class="form-control" autocomplete="false" placeholder="Enter the year, make, and model of the bike you would like us to get for you." %}
                {% if form.content.errors %}
                    <span class="help-block">
                    {% for error in form.content.errors %}{{ error }}{% endfor %}
                    </span>
                {% endif %}
            </div>
        </div>
        <br>
        <div class="text-center">
        <button type="submit" class="btn btn-primary submit-button">Submit Request</button>
        </div>
        <br>
    </form>
    </div> 
    </div>
</div>
</div>
{% endblock %}